### PR TITLE
add go-debug

### PR DESCRIPTION
**Pull request by lloiser**
Haven't touched CI scripts `.travis.yml` and `appveyor.yml`.

### CODE REVIEW

**Comment by andrewrgoss** [comment]
Can we get a timeline on when this will be merged into the go-plus package? Dying to have an interactive debugger for Golang akin to the experience Visual Studio provides...

**Comment by joefitzgerald** [comment]
@andrewrgoss you're not blocked at all? Just install `go-debug` via the Atom UI or via `apm install go-debug` on the command line (requires a restart if you use `apm`.

**Comment by joefitzgerald** [comment]
To answer your question about a timeline for merging: I want to ensure we have a way to automate the installation of delve on the target machine. Without it, we'll get buried with questions about why debugging isn't working. Alternatively we could ship with support for [`godebug`](https://github.com/mailgun/godebug) as it is "go gettable" and allow for the user to select delve as an option (until we figure out how to automate the installation).

**Comment by andrewrgoss** [comment]
@joefitzgerald appreciate the quick response here, I did install `go-debug` via the Atom UI, however I can't get delve successfully installed after multiple attempts. Unfortunately the documentation is extremely poor for both `go-debug` and `delve`, which is why I was hoping this would be integrated into `go-plus`.

**Comment by joefitzgerald** [comment]
Hehe, this is precisely why this PR has not been merged yet. Suggest you work with @lloiser on getting things going (but first just work with the delve community to get delve installed correctly) and then maybe we can find a way to automate the steps you had to take. Ideally delve would just be released as a binary that could be downloaded from github releases.

**Comment by andrewrgoss** [comment]
Having `delve` be a simple downloaded binary would be a beautiful, simple thing indeed. I'll see what I can find out. Thanks again for the help.

**Comment by lloiser** [comment]
@andrewrgoss feel free to contact me on slack https://gophersinvite.herokuapp.com/ (go-plus channel) or direct message if you need help

**Comment by joefitzgerald** [comment]
:shipit:

**Pull request merged**
