### PR TITLE
adds the ability to define a custom directory for test and coverage runner

### PR DESCRIPTION
**Pull request by xpressivecode**

### CODE REVIEW

**Comment by joefitzgerald** [comment]
What's the motivator for this?

**Comment by xpressivecode** [comment]
There was a question in slack. It seems that some individuals restrict exec access to their tmp dir. Either by choice or as a company policy. Thought it might help, vs always having to run something like ```TMPDIR=/custom atom .```

**Comment by joefitzgerald** [comment]
It seems this only happens on certain operating systems. Maybe we could make this automatic in some way?

**Comment by xpressivecode** [comment]
It looked like there was some debate in regards to where build artifacts should end up. So automating it looked like it may upset a few people, vs letting them decide. Maybe updating the FAQ to suggest running ```TMPDIR=/custom atom .``` and removing this pr is enough instead?

**Comment by joefitzgerald** [comment]
Opened #722 to document `TMPDIR=/custom atom .`.

**Pull request closed without merging**
