### PR TITLE
[WIP] Add support for gorename (fixes #91)

### LINKED ISSUE #91: Add support for gorename
There is a new tool added to the tools repository that looks interesting; gorename. The tool allows you to easily rename identifiers across a project. Might be worth a look.

https://groups.google.com/d/msg/golang-nuts/96hGPXYfqsM/WreOUy9qOT4J

### PR DESCRIPTION
**Pull request by zmb3**
This requires a gorename binary from today (17 March 2015) or newer.
See https://github.com/golang/tools/commit/22067118645556995c55964f3e5c82470e0b0c9f#diff-b8510c3666f3b544a8edadfeaa9e750a

TO DO

- [x] The output of gorename is duplicated in the go-plus message panel
- [x] All unsaved *.go files should be saved before invoking gorename (not
  just the current one)
- [ ] lib/dialog.coffee is copied from atom-tree-view (how do we reuse this?)
- [ ] add specs
- [x] support multi-byte characters (gorename accepts a byte offset, not a character offset)

### CODE REVIEW

**Comment by zmb3** [comment]
Here's an example:
goplus-rename

**Comment by joefitzgerald** [comment]
@zmb3 thanks for this! I know I need to review this - I will do so as soon as possible!

**Comment by joefitzgerald** [comment]
> All unsaved *.go files should be saved before invoking gorename (not just the current one)

`atom.workspace.getTextEditors()`, loop through them all and call editor.save(), optionally checking editor.getBuffer().isModified() and only saving when that is true.

**Comment by mishak87** [comment]
:+1: I will do some user testing when it is out.

**Comment by fourcube** [comment]
:+1: Same here. This is gonna be huge for productivity. Thanks @zmb3!

**Comment by svanharmelen** [comment]
+1

**Comment by joefitzgerald** [comment]
@zmb3 what's the status on this? I would love to merge this. Could you let me know what is left, and whether you'd like to finish it off (or have me take it the last mile)?

**Comment by zmb3** [comment]
Hey Joe,

It's been a while since I looked at this.  I need to rebase, and then there are a few issues remaining.  I'd be glad to work them, but I'd need some help.  I'm also fine with you just finishing them off - I'll watch and learn!  I got about as far as could be expected for someone who's never written any CoffeeScript (or JavaScript, for that matter) :stuck_out_tongue:  

The remaining issues listed above are accurate. The biggest one I think is converting the position from a character index that Atom provides to a byte index that gorename wants.

I also couldn't figure out how to reuse the rename view, so I ended up copying some source from the tree view package. I'm not too fond of this.

Lastly, it really needs some tests.

**Comment by zmb3** [comment]
FYI - I have a change to gorename to handle rune offsets instead of byte offsets.  It's pending review now: https://go-review.googlesource.com/#/c/12725/

**Comment by jpillora** [comment]
:+1: on getting this merged

**Comment by joefitzgerald** [comment]
I'm looking forward to it also @jpillora - just waiting for @zmb3 to give me the all-clear that he's done with the PR and it's no longer WIP.

**Comment by joefitzgerald** [comment]
@zmb3 the byte index bits seem related to #276.

**Comment by zmb3** [comment]
Yeah I took care of the byte index yesterday.  I was hoping there was a more efficient way to do it, but this seems to work fine.

All that's left is to write some tests.  I tried but couldn't quite figure it out.  Would you mind helping out on that part?

**Comment by jchannon** [comment]
Awesome, can't wait for this to drop

**Comment by zmb3** [comment]
I'm going to go ahead and close this one.

For those interested, `gorename` integration will be provided as a separate package which will be bundled with go-plus when it's ready.  Follow along here: https://github.com/zmb3/gorename

**Pull request closed without merging**
