### PR TITLE
WIP: fix some invalid suggestions

### PR DESCRIPTION
**Pull request by lloiser**
🚨  **WIP** 🚨 

This merge request attempts to fix some invalid suggestions that exist since the switch to fuzzy matching and caching of `gocode` results.

I will add more comments on how to reproduce a certain problem and (if easily possible) also a unittest (that obviously will fail for the moment)

### CODE REVIEW

**Comment by lloiser** [comment]
### GIVEN

```go
import "fmt"

func main() {
	foo := "bar"
	fmt.Printf(foo)

}
```

The cursor is currently at the empty line after `fmt.Printf`

### WHEN

I start typing `fmt.Printf(` (character by character)

And finally write `f` again.

### THEN

**Expected**

I get a suggestion for `foo`

**Actual**

I get (again) suggestions for the `fmt` package like `Printf`, `Errorf`, etc...

**Comment by joefitzgerald** [comment]
What else needs to be done on this?

**Comment by lloiser** [comment]
I still get wrong suggestions from time to time but it's really difficult to reproduce it and even harder in a unittest...

tbh I think we should change the current behaviour to match the one implemented in the atom-languageclient: https://github.com/atom/atom-languageclient/pull/128. It seems like a sound solution.

**Comment by lloiser** [comment]
### GIVEN

```go
import "fmt"

func main() {
	fmt.Errorf("my error")
}
```

The cursor is currently at the empty line after `fmt.Printf`

### WHEN

add a `.` after `fmt.Errorf("asdf")`

### THEN

**Expected**

I get a suggestions for the returned error, so `String()`

**Actual**

I get nothing

**Comment by tj** [comment]
I can't quite narrow down a specific pattern, but matching definitely seems a bit messed up lately, even if you have a `Decoder` struct in the file for example it'll just ignore it entirely (unless that's a gocode issue)

**Pull request closed without merging**
