### PR TITLE
Go generate specs and feature added

### PR DESCRIPTION
**Pull request by mrkaspa**
I added support for go generate command

### CODE REVIEW

**Comment by mrkaspa** [comment]
I think the tests need this command line installed https://godoc.org/github.com/Go-zh/tools/cmd/stringer I'll figure out another way to test it

**Comment by mrkaspa** [comment]
@joefitzgerald do you have an idea about how to test this without installing the command line?

**Comment by joefitzgerald** [comment]
Thanks! Just add a go get for stringer to .travis.yml and appveyor.yml.

**Comment by mrkaspa** [comment]
@joefitzgerald I think it worked but it threw errors in other specs https://travis-ci.org/joefitzgerald/go-plus/builds/72760896 I got that same result locally

**Comment by joefitzgerald** [comment]
Thanks for this contribution; I'm going to close this due to the age, but I'm still open to providing a way to run go generate as needed. I personally just run it in the terminal when I make changes requiring another generate run.

**Pull request closed without merging**
