### PR TITLE
Join forces of go-oracle and go-plus!

### PR DESCRIPTION
**Pull request by rubyist**
This PR will join the magnificent forces of go-oracle with go-plus, creating the most magnificent Go development package ever conceived :sparkles:.

Things To Do:
- [x] Import the base package
- [x] Look for and :bomb: any duplicate code
- [ ] Mold the go-oracle code into the go-plus style - use atom message panel
- [ ] :skull: any remaining go-oracle :bug:
- [ ] :skull: the go-oracle package, :point_right: it to go-plus

### CODE REVIEW

**Comment by santagada** [comment]
Any updates on this? Having callees and callers inside atom would be the missing feature from intelij go plugin.

**Comment by binary132** [comment]
I too would be very interested in having this feature functional!

**Comment by jcmartins** [comment]
:+1:

**Comment by wayne-luminal** [comment]
Would love to see this integration

**Comment by jims** [comment]
Please resurrect this! Would be so awesome!

**Pull request closed without merging**
