### PR TITLE
Fix for error when saving test files / empty go files

### PR DESCRIPTION
**Pull request by fourcube**
Proposed fix for joefitzgerald/go-plus#125

### CODE REVIEW

**Comment by fourcube** [comment]
@joefitzgerald this also fixes #153.

**Comment by joefitzgerald** [comment]
LGTM :+1:

**Comment by joefitzgerald** [comment]
Actually, why are we running gofmt synchronously?

**Comment by fourcube** [comment]
When gofmt reformats the file with the "-w" flag and the execution happens asynchronously, I noticed that the following things happen: 

- The exec callback is invoked
- The buffer is empty (split second)
- All other tools start running ([this spot]) and `gobuild` throws an error (#153, #125 )
- The buffer displays the formatted content

Atom seems to update the buffer's content twice when running `gofmt` asynchronously, whereas the buffer is only updated once, when `gofmt` is executed synchronously.

[this spot]: https://github.com/fourcube/go-plus/blob/533bec5bb6404420ce88332075823e82941058fb/lib/dispatch.coffee#L286

**Pull request merged**
