### PR TITLE
Linter support: https://atom.io/packages/linter

### PR DESCRIPTION
**Pull request by greensnark**
Make go-plus an atom-linter provider for warning and error messages. This is controlled by the new useAtomLinter setting which defaults to true.

(atom-linter provides gutter annotations and navigation between errors/warnings, and is actively maintained.)

The atom linter option is set to true by default, and will automatically be preferred to atom-message-panel if both are available.

### CODE REVIEW

**Comment by greensnark** [comment]
Not sure why AppVeyor build is failing...

**Comment by zmb3** [comment]
I think Joe's been planning to use atom-linter for a while (as part of #213) but there's some work re: runtime detection that still needs to be done.

**Comment by greensnark** [comment]
@zmb3 Thanks for the word, I'll leave this up and hope it doesn't duplicate work Joe's already done.

**Comment by greensnark** [comment]
The AppVeyor build failure is pretty interesting: the atom process that `apm test` spawns is exiting with code -1073741819 which is suspiciously identical to 0xC0000005, viz. Windows' Access Violation / segfault. I can reproduce this on a Windows VM with Atom 1.0.19. The crash seems unrelated to this pull request since I can replicate it easily with many other atom packages.

**Comment by sztanpet** [comment]
may i also suggest using gometalinter as the linter? it has so many useful tools including all the ones already included

**Comment by joefitzgerald** [comment]
Update: https://atom.io/packages/gometalinter-linter.

**Comment by joefitzgerald** [comment]
Hey @greensnark thanks so much for the contribution! It helped me significantly in my implementation of gometalinter-linter.

**Pull request closed without merging**
